export const AUTO_LANGUAGE = 'auto'

export const SUPPORTED_LANGUAGES = {
  en: 'English',
  es: 'Español',
  fr: 'Français',
  de: 'Deutsch',
  it: 'Italiano',
  pt: 'Português',
  ru: 'Русский',
  ja: '日本語',
  ko: '한국어',
  zh: '中文',
  ar: 'العربية',
  tr: 'Türkçe',
  pl: 'Polski',
  nl: 'Nederlands',
  hu: 'Magyar',
  id: 'Bahasa Indonesia',
  cs: 'Čeština',
  sv: 'Svenska',
  da: 'Dansk',
  fi: 'Suomi',
  nb: 'Norsk',
  he: 'עברית',
  th: 'ไทย',
  vi: 'Tiếng Việt',
  uk: 'Українська',
  el: 'Ελληνικά',
  ro: 'Română',
  sk: 'Slovenčina',
  bg: 'Български',
  hr: 'Hrvatski',
  lt: 'Lietuvių',
  sl: 'Slovenščina',
  sr: 'Српски',
  fil: 'Filipino',
  lv: 'Latviešu',
  et: 'Eesti',
  ms: 'Bahasa Melayu',
  is: 'Íslenska',
  sw: 'Kiswahili',
  ga: 'Gaeilge',
  sq: 'Shqip',
  hi: 'हिन्दी',
  fa: 'فارسی',
  bn: 'বাংলা',
  ta: 'தமிழ்',
  te: 'తెలుగు',
  ml: 'മലയാളം',
  kn: 'ಕನ್ನಡ',
  mr: 'मराठी',
  gu: 'ગુજરાતી',
  pa: 'ਪੰਜਾਬੀ',
  ne: 'नेपाली',
  si: 'සිංහල',
  ug: 'ئۇيغۇرچە',
  km: 'ភាសាខ្មែរ',
  my: 'မြန်မာဘာသာ',
  az: 'Azərbaycan',
  kk: 'Қазақ',
  uz: 'O‘zbek',
  mn: 'Монгол хэл',
  hy: 'Հայերեն',
  af: 'Afrikaans',
  ka: 'ქართული',
  eu: 'Euskara',
  gl: 'Galego',
  isv: 'Interlingua',
  ia: 'Interlingua',
  la: 'Latina',
  oc: 'Occitan',
  cy: 'Cymraeg',
  eo: 'Esperanto',
  tlh: 'Klingon',
  tlhQaak: 'Klingon (pIqaD)',
  xh: 'isiXhosa',
  zu: 'isiZulu',
  haw: 'ʻŌlelo Hawaiʻi',
  jbo: 'Lojban',
  tl: 'Tagalog',
  tet: 'Tetun',
  ur: 'اردو',
  tg: 'Тоҷикӣ',
  tk: 'Туркмен',
  cv: 'Чӑвашла',
  uzCyrl: 'Ўзбек',
  bnIn: 'বাংলা (ভারত)',
  mni: 'মৈতৈলোন্',
  as: 'অসমীয়া',
  kok: 'कोंकणी',
  br: 'Brezhoneg',
  ugArab: 'ئۇيغۇرچە',
  mi: 'Māori',
  qu: 'Runa Simi',
  quz: 'Runasimi',
  nso: 'Sesotho sa Leboa',
  tn: 'Setswana',
  xbr: 'Kambera',
  nd: 'isiNdebele',
  wa: 'walon',
  sc: 'sardu',
  co: 'corsu',
  gsw: 'Schwiizertüütsch',
  rm: 'rumantsch',
  st: 'Sesotho',
  ts: 'Xitsonga',
  ss: 'siSwati',
  ve: 'Tshivenḓa',
  nr: 'isiNdebele',
  wo: 'Wolof',
  fy: 'Frysk',
  lb: 'Lëtzebuergesch',
  mg: 'Malagasy',
  ku: 'Kurdî',
  kuArab: 'کوردی',
  kuLatn: 'Kurdî'
}
